name: Release

jobs:
  release:
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate release notes
        id: notes
        run: |
          git fetch --prune --unshallow
          git log $(git describe --tags --abbrev=0)..HEAD --pretty=format:'* %s' > release_notes.md
          echo "::set-output name=notes::$(cat release_notes.md)"

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag: ${{ github.ref }}
          release_notes: ${{ steps.notes.outputs.notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
